name: Secret Scan

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run Gitleaks to scan the code
      - name: Run Gitleaks to detect secrets
        uses: zricethezav/gitleaks-action@v2.1.0
        with:
          args: detect --source . --verbose

      # Optional: Upload report as artifact
      - name: Upload Gitleaks report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-report
          path: gitleaks-report.json
